name: Trigger Review Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  trigger:
      uses: paradigma-spa/pr-reviewer/.github/workflows/generate_review.yml@main
      with:
        pr_number: ${{ github.event.pull_request.number }}
        repository: ${{ github.repository }}
